// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXatOljwFUKQHYofCe69zpfdOuMkQNcis',
    appId: '1:276245144384:web:22bdfc2690a39694b690a5',
    messagingSenderId: '276245144384',
    projectId: 'skill-exchange-app-80674',
    authDomain: 'skill-exchange-app-80674.firebaseapp.com',
    storageBucket: 'skill-exchange-app-80674.firebasestorage.app',
    measurementId: 'G-3JJPJDHMYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdNn6yZiejU1Pep4HFnR1aaKNr3KEr0UE',
    appId: '1:276245144384:android:37341c2e1dac6687b690a5',
    messagingSenderId: '276245144384',
    projectId: 'skill-exchange-app-80674',
    storageBucket: 'skill-exchange-app-80674.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKEE89kFHzzv85CPbq4vk5kOvgeA8wACc',
    appId: '1:276245144384:ios:98a85b0dfb257476b690a5',
    messagingSenderId: '276245144384',
    projectId: 'skill-exchange-app-80674',
    storageBucket: 'skill-exchange-app-80674.firebasestorage.app',
    iosBundleId: 'com.example.skillExchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKEE89kFHzzv85CPbq4vk5kOvgeA8wACc',
    appId: '1:276245144384:ios:98a85b0dfb257476b690a5',
    messagingSenderId: '276245144384',
    projectId: 'skill-exchange-app-80674',
    storageBucket: 'skill-exchange-app-80674.firebasestorage.app',
    iosBundleId: 'com.example.skillExchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXatOljwFUKQHYofCe69zpfdOuMkQNcis',
    appId: '1:276245144384:web:7ec1094ae74edd6ab690a5',
    messagingSenderId: '276245144384',
    projectId: 'skill-exchange-app-80674',
    authDomain: 'skill-exchange-app-80674.firebaseapp.com',
    storageBucket: 'skill-exchange-app-80674.firebasestorage.app',
    measurementId: 'G-YNDGXYHZWV',
  );
}
